DataMarkup/Controllers/MarkupTasksController.cs
using DataMarkup.Data;
using DataMarkup.Models;
using DataMarkup.ViewModels;
using Mapster;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DataMarkup.Controllers;

public class MarkupTasksController : Controller
{
    private readonly DataMarkupContext _dataMarkupContext;
    private readonly UserManager<User> _userManager;

    public MarkupTasksController(DataMarkupContext dataMarkupContext, UserManager<User> userManager)
    {
        _dataMarkupContext = dataMarkupContext;
        _userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> Board()
    {
        if (!User.Identity!.IsAuthenticated)
            return RedirectToAction("NeedsAuthorization", "Home");

        var userId = Guid.Parse(_userManager.GetUserId(User));
        var user = await _dataMarkupContext.Users
            .Include(user => user.MarkupTasks)
            .SingleAsync(user => user.Id == userId);

        return View(user.MarkupTasks);
    }

    [HttpGet]
    public IActionResult Create() => User.Identity!.IsAuthenticated ?
        View(new MarkupTaskViewModel
        {
            CurrentQuestion = new MarkupQuestionViewModel(),
            Questions = new List<MarkupQuestionViewModel>()
        }) :
        Unauthorized();

    [HttpPost]
    public async Task<IActionResult> Create([FromBody]MarkupTaskViewModel taskViewModel)
    {
        if (!ModelState.IsValid)
            return BadRequest();

        if (!User.Identity!.IsAuthenticated)
            return RedirectToAction("NeedsAuthorization", "Home");

        if (!ModelState.IsValid)
            return View(taskViewModel);

        var currentUser = await _userManager.GetUserAsync(User);
        var markupTask = taskViewModel.Adapt<MarkupTask>() with
        {
            Id = Guid.NewGuid(),
            User = currentUser,
            Questions = taskViewModel.Questions
                .Select(questionViewModel => questionViewModel.Adapt<MarkupQuestion>())
                .ToList()
        };

        _dataMarkupContext.Tasks.Add(markupTask);

        await _dataMarkupContext.SaveChangesAsync();

        return Ok();
    }

    [HttpPost]
    public async Task<IActionResult> EditTask([FromBody]MarkupTaskViewModel taskViewModel)
    {
        if (!ModelState.IsValid)
            return BadRequest();

        if (!User.Identity!.IsAuthenticated)
            return RedirectToAction("NeedsAuthorization", "Home");

        var userId = Guid.Parse(_userManager.GetUserId(User));
        var user = await _dataMarkupContext.Users
            .Include(user => user.MarkupTasks)
            .SingleAsync(user => user.Id == userId);

        var task = user.MarkupTasks.SingleOrDefault(task => task.Id == taskViewModel.Id);

        if (task is null)
            return Forbid();

        task.Name = taskViewModel.Name;
        task.MaxSolutions = taskViewModel.MaxSolutions;
        task.Payment = taskViewModel.Payment;
        task.Instruction = taskViewModel.Instruction;

        await _dataMarkupContext.SaveChangesAsync();

        return Ok();
    }

    public async Task<IActionResult> EditQuestion([FromBody]MarkupQuestionViewModel questionViewModel)
    {
        if (!ModelState.IsValid)
            return BadRequest();

        if (!User.Identity!.IsAuthenticated)
            return Unauthorized();

        var userId = Guid.Parse(_userManager.GetUserId(User));

        var question = await _dataMarkupContext.Tasks
            .Include(task => task.Questions)
            .Include(task => task.User)
            .Where(task => task.User.Id == userId)
            .SelectMany(task => task.Questions)
            .SingleOrDefaultAsync(question => question.Id == questionViewModel.Id);

        if (question is null)
            return Forbid();


        question.StaticContent = questionViewModel.StaticContent;
        question.DynamicContentConstraint = questionViewModel.DynamicContentConstraint;
        question.AnswerDescription = questionViewModel.AnswerDescription;

        await _dataMarkupContext.SaveChangesAsync();

        return Ok();
    }

    [HttpGet("/{id:guid}")]
    public async Task<IActionResult> GetTask(Guid id)
    {
        if (!User.Identity!.IsAuthenticated)
            return Unauthorized();

        var task = await _dataMarkupContext.Tasks
            .Include(task => task.User)
            .Include(task => task.Questions)
            .SingleOrDefaultAsync(task => task.Id == id);

        if (task is null)
            return NotFound();

        var userId = Guid.Parse(_userManager.GetUserId(User));

        if (task.User.Id != userId)
            return Forbid();

        var taskViewModel = task.Adapt<MarkupTaskViewModel>() with
        {
            Questions = task.Questions
                .Select(question => question.Adapt<MarkupQuestionViewModel>())
                .ToList()
        };

        return View(taskViewModel);
    }
}

DataMarkup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] DataMarkup</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DataMarkup</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-start" id="navbarLeft">
            @if (User.Identity!.IsAuthenticated)
            {
                <a class="navbar-text text-light mr-3" asp-controller="MarkupTasks" asp-action="Board">Tasks Board</a>
            }
        </div>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarRight">
            @if (User.Identity!.IsAuthenticated)
            {
                <span class="navbar-text text-light mr-2">@User.Identity.Name</span>
                <form method="post" asp-controller="Account" asp-action="Logout" class="form-inline">
                    <input type="submit" class="btn btn-outline-light" value="Logout"/>
                </form>
            }
            else
            {
                <a class="navbar-link text-light mr-2" asp-controller="Account" asp-action="Login">
                    Login
                </a>
                <a class="navbar-link text-light" asp-controller="Account" asp-action="Registration">
                    Registration
                </a>
            }
        </div>
    </nav>
</header>
<div class="container-fluid">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>